version: "{build}"
skip_non_tags: true
environment:
  NuGetApiKey:
    secure: 23+pfmN1D6MWK5DKZNxxX1R3VxBJ/Dn8/wVzJWqV7RvJcBoffGEx96hfa/fPOHyW
install:
  - ps: Install-Module psake, Pester
build: false
test_script:
  - ps: |-
      Invoke-psake ./psakefile.ps1 test

      if ($LASTEXITCODE -gt 0) {
        throw 'Tests failed'
      }
artifacts:
  - path: Module
    name: $(APPVEYOR_PROJECT_NAME)
before_deploy:
  - ps: Invoke-psake ./psakefile.ps1 InitializeDeployments
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(RELEASE_DESCRIPTION)
    auth_token:
      secure: +PxazkcvZpF9LLVySBX9zDKxps/khE1StNaoo8/brhcbOrtZAxL9fwWc2wmvCRia+cGSBx7z0HOqKy35wz9UMk40XWgu/4Q2zioye6Dtui40OvMDaQsPBH7wcAkIvsBG
    artifact: $(APPVEYOR_PROJECT_NAME)
    prerelease: $(IS_PRERELEASE)
    on:
      APPVEYOR_REPO_TAG: true
after_deploy:
  - ps: Invoke-psake ./psakefile.ps1 DeployToPowerShellGallery
on_finish:
  # Upload test results on build finish (after_test will not run on a failed build)
  - ps: Invoke-psake ./psakefile.ps1 UploadTestResults
