version: "{build}"
skip_non_tags: true
init:
  - ps: |-
      function Start-Task {
        param([string] $Task)

        Invoke-psake -buildFile ./psakefile.ps1 -taskList $Task -nologo -notr

        if (-not $psake.build_success) {
          exit 1
        }
      }
environment:
  NuGetApiKey:
    secure: 23+pfmN1D6MWK5DKZNxxX1R3VxBJ/Dn8/wVzJWqV7RvJcBoffGEx96hfa/fPOHyW
install:
  - ps: Install-Module psake, Pester
build: false
test_script:
  - ps: Start-Task Test
artifacts:
  - path: Module
    name: $(APPVEYOR_PROJECT_NAME)
before_deploy:
  - ps: Start-Task InitializeDeployments
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(RELEASE_DESCRIPTION)
    auth_token:
      secure: +PxazkcvZpF9LLVySBX9zDKxps/khE1StNaoo8/brhcbOrtZAxL9fwWc2wmvCRia+cGSBx7z0HOqKy35wz9UMk40XWgu/4Q2zioye6Dtui40OvMDaQsPBH7wcAkIvsBG
    artifact: $(APPVEYOR_PROJECT_NAME)
    prerelease: $(IS_PRERELEASE)
    on:
      APPVEYOR_REPO_TAG: true
after_deploy:
  - ps: Start-Task DeployToPowerShellGallery
on_finish:
  # Upload test results on build finish (after_test will not run on a failed build)
  - ps: Start-Task UploadTestResults
